name: "Shoko"
guid: "5216ccbf-d24a-4eb3-8a7e-7da4230b7052"
imageUrl: https://raw.githubusercontent.com/ShokoAnime/Shokofin/master/LogoWide.png
targetAbi: "10.8.0.0"
owner: "shokoanime"
overview: "Manage your anime from Jellyfin using metadata from Shoko"
description: >
  A plugin to provide metadata from Shoko Server for your locally organized anime library in Jellyfin.
category: "Metadata"
artifacts:
- "Shokofin.dll"
changelog: >
  NA
