name: Shokofin Bug Report 101
description: Report any bugs here!
labels: []
projects: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Shokofin Bug Report
        **Important:** This form is exclusively for reporting bugs. If your issue is not due to a bug but you requires assistance (e.g. with setup) or if you just have a question or inquiry, then please seek help on our [Discord](https://discord.gg/shokoanime) server instead. Our Discord community is eager to assist, and we often respond faster and can provide more immediate support on Discord.

        To help us understand and resolve your bug report more efficiently, please fill out the following information.

        And remember, for quicker assistance on any inquiries, Discord is the way to go!
  - type: input
    id: jelly
    attributes:
      label: Jellyfin version.
      placeholder: "E.g. `10.8.12`"
    validations:
      required: true
  - type: input
    id: shokofin
    attributes:
      label: Shokofin version.
      placeholder: "E.g. `3.0.1.0`"
    validations:
      required: true
  - type: input
    id: Shokoserver
    attributes:
      label: Shoko Server version, release channel, and commit hash.
      placeholder: "E.g. `1.0.0 Stable` or  `1.0.0 Dev (efefefe)`"
    validations:
      required: true
  - type: textarea
    id: fileStructure
    attributes:
      label: File structure of your _Media Library Folder in Jellyfin_/_Import Folder in Shoko Server_.
      placeholder: "E.g. ../Anime A/Episode 1.avi or ../Anime A/Season 1/Episode 1.avi"
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot of the "library settings" section of the plugin settings.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Library type and metadata/image providers enabled for the library/libaries in Jellyfin.
  - type: dropdown
    id: library
    attributes:
      label: Library Type(s).
      multiple: true
      options:
        - Shows
        - Movies
        - Movies & Shows
    validations:
      required: true
  - type: checkboxes
    id: metadataCheck
    attributes:
      label: "Do the issue persists after creating a library with Shoko set as the only metadata provider? (Now is your time to check if you haven't already.)"
      options:
        - label: "Yes, I hereby confirm that the issue persists after creating a library with Shoko set as the only metadata provider."
          required: true
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: Issue
      description: Try to explain your issue in simple terms. We'll ask for details if it's needed.
    validations:
      required: true
  - type: textarea
    id: stackTrace
    attributes:
      label: Stack Trace
      description: If relevant, paste here.
