name: Shokofin Feature Request 101
description: Request your features here!
labels: []
projects: []
assignees:
  - revam
body:
  - type: markdown
    attributes:
      value: |
        **Feature Request**
        Suggest a request or idea that will help the project!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the feature you would like to request.
      placeholder: Describe your feature here.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Suggested Solution
      description: How would you like the feature to be implemented?
      placeholder: Describe your solution here.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any additional information you would like to provide?
      placeholder: Provide any additional information here.