name: Shokofin Issue Report 101
description: Report your issues here!
labels: []
projects: []
assignees:
  - revam
body:
  - type: markdown
    attributes:
      value: |
        ## Shokofin Issue Report
        Please fill out the following information to help us understand your issue better, we respond faster on [Discord](https://discord.gg/shokoanime) <br />
        If you are facing setup issues use discord, we'll be happy to help you. <br />
        **Note:** This template is for bug reports only, if you require another form of assistance please use the Discord server.
  - type: input
    id: jelly
    attributes:
      label: Jellyfin version.
      placeholder: "E.g. `10.8.12`"
    validations:
      required: true
  - type: input
    id: shokofin
    attributes:
      label: Shokofin version.
      placeholder: "E.g. `3.0.1.0`"
    validations:
      required: true
  - type: input
    id: Shokoserver
    attributes:
      label: Shoko Server version, release channel, and commit hash.
      placeholder: "E.g. `1.0.0 Stable` or  `1.0.0 Dev (efefefe)`"
    validations:
      required: true
  - type: textarea
    id: fileStructure
    attributes:
      label: File structure of your _Media Library Folder in Jellyfin_/_Import Folder in Shoko Server_.
      placeholder: "E.g. ../Anime A/Episode 1.avi or ../Anime A/Season 1/Episode 1.avi"
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot of the "library settings" section of the plugin settings.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Library type and metadata/image providers enabled for the library/libaries in Jellyfin.
  - type: checkboxes
    id: library
    attributes:
      label: "Library Type:"
      options:
        - label: Shows
        - label: Movies
        - label: Movies & Shows
    validations:
      required: true
  - type: checkboxes
    id: metadataCheck
    attributes:
      label: "Have you tried creating a library with only Shoko as metadata provider?"
      options:
        - label: "Yes"
          required: true
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: Your Issue
      description: Try to explain your issue in simple terms. We'll ask for details if it's needed.
    validations:
      required: true
  - type: textarea
    id: stackTrace
    attributes:
      label: Stack Trace
      description: If relevant, paste here.