name: Unstable Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Release (Unstable)

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Replace Sentry DSN key
        shell: pwsh
        run: ./.github/workflows/ReplaceSentryDSN.ps1 -dsn ${{ secrets.SENTRY_DSN }}

      - name: Get previous release version
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0

      - name: Setup .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore Nuget Packages
        run: dotnet restore Shokofin/Shokofin.csproj

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install JPRM
        run: python -m pip install jprm

      - name: Run JPRM
        run: echo "NEW_VERSION=$(python build_plugin.py --version=${{ steps.previoustag.outputs.tag }} --prerelease=True)" >> $GITHUB_ENV

      - name: Create Pre-Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/shoko_*.zip
          tag_name: ${{ env.NEW_VERSION }}
          prerelease: true
          fail_on_unmatched_files: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Unstable Manifest
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: "misc: update unstable manifest"
          file_pattern: manifest-unstable.json
          skip_fetch: true

      - name: Push Sentry release "${{ env.NEW_VERSION }}"
        uses: getsentry/action-release@v1.2.1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          # SENTRY_URL: https://sentry.io/
        with:
          environment: 'dev'
          version: ${{ env.NEW_VERSION }}
