name: Stable Release

on:
  release:
    types:
      - released
    branches: master

jobs:
  build_plugin:
    runs-on: ubuntu-latest
    name: Build Release

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0 # This is set to download the full git history for the repo

      - name: Get Current Version
        id: release_info
        uses: revam/gh-action-get-tag-and-version@v1
        with:
          branch: true
          prefix: v
          prefixRegex: "[vV]?"

      - name: Setup .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore Nuget Packages
        run: dotnet restore Shokofin/Shokofin.csproj

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install JPRM
        run: python -m pip install jprm

      - name: Run JPRM
        env:
          CHANGELOG: "" # Add the release's change-log here maybe.
        run: python build_plugin.py --repo ${{ github.repository }} --version=${{ steps.current_info.outputs.version }}

      - name: Update Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./artifacts/shoko_*.zip
          tag: ${{ github.ref }}
          file_glob: true

      - name: Update Stable Manifest
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: "misc: update stable manifest"
          file_pattern: manifest.json
          skip_fetch: true
